apps/authentication/models.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask_login import UserMixin

from apps import db, login_manager

from apps.authentication.util import hash_pass

class Users(db.Model, UserMixin):

    __tablename__ = 'Users'

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), unique=True)
    email = db.Column(db.String(64), unique=True)
    password = db.Column(db.LargeBinary)

    def __init__(self, **kwargs):
        for property, value in kwargs.items():
            # depending on whether value is an iterable or not, we must
            # unpack it's value (when **kwargs is request.form, some values
            # will be a 1-element list)
            if hasattr(value, '__iter__') and not isinstance(value, str):
                # the ,= unpack of a singleton fails PEP8 (travis flake8 test)
                value = value[0]

            if property == 'password':
                value = hash_pass(value)  # we need bytes here (not plain str)

            setattr(self, property, value)

    def __repr__(self):
        return str(self.username)


@login_manager.user_loader
def user_loader(id):
    return Users.query.filter_by(id=id).first()


@login_manager.request_loader
def request_loader(request):
    username = request.form.get('username')
    user = Users.query.filter_by(username=username).first()
    return user if user else None

apps/authentication/forms.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField
from wtforms.validators import Email, DataRequired

# login and registration


class LoginForm(FlaskForm):
    username = StringField('Username',
                         id='username_login',
                         validators=[DataRequired()])
    password = PasswordField('Password',
                             id='pwd_login',
                             validators=[DataRequired()])


class CreateAccountForm(FlaskForm):
    username = StringField('Username',
                         id='username_create',
                         validators=[DataRequired()])
    email = StringField('Email',
                      id='email_create',
                      validators=[DataRequired(), Email()])
    password = PasswordField('Password',
                             id='pwd_create',
                             validators=[DataRequired()])

apps/__init__.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask import Flask
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy
from importlib import import_module


db = SQLAlchemy()
login_manager = LoginManager()


def register_extensions(app):
    db.init_app(app)
    login_manager.init_app(app)


def register_blueprints(app):
    for module_name in ('authentication', 'home'):
        module = import_module('apps.{}.routes'.format(module_name))
        app.register_blueprint(module.blueprint)


def configure_database(app):

    @app.before_first_request
    def initialize_database():
        db.create_all()

    @app.teardown_request
    def shutdown_session(exception=None):
        db.session.remove()


def create_app(config):
    app = Flask(__name__)
    app.config.from_object(config)
    register_extensions(app)
    register_blueprints(app)
    configure_database(app)
    return app

apps/authentication/__init__.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask import Blueprint

blueprint = Blueprint(
    'authentication_blueprint',
    __name__,
    url_prefix=''
)

apps/authentication/routes.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask import render_template, redirect, request, url_for
from flask_login import (
    current_user,
    login_user,
    logout_user
)

from apps import db, login_manager
from apps.authentication import blueprint
from apps.authentication.forms import LoginForm, CreateAccountForm
from apps.authentication.models import Users

from apps.authentication.util import verify_pass

@blueprint.route('/')
def route_default():
    return redirect(url_for('authentication_blueprint.login'))

# Login & Registration

@blueprint.route('/login', methods=['GET', 'POST'])
def login():
    login_form = LoginForm(request.form)
    if 'login' in request.form:

        # read form data
        username = request.form['username']
        password = request.form['password']

        # Locate user
        user = Users.query.filter_by(username=username).first()

        # Check the password
        if user and verify_pass(password, user.password):

            login_user(user)
            return redirect(url_for('authentication_blueprint.route_default'))

        # Something (user or pass) is not ok
        return render_template('accounts/login.html',
                               msg='Wrong user or password',
                               form=login_form)

    if not current_user.is_authenticated:
        return render_template('accounts/login.html',
                               form=login_form)
    return redirect(url_for('home_blueprint.index'))


@blueprint.route('/register', methods=['GET', 'POST'])
def register():
    create_account_form = CreateAccountForm(request.form)
    if 'register' in request.form:

        username = request.form['username']
        email = request.form['email']

        # Check usename exists
        user = Users.query.filter_by(username=username).first()
        if user:
            return render_template('accounts/register.html',
                                   msg='Username already registered',
                                   success=False,
                                   form=create_account_form)

        # Check email exists
        user = Users.query.filter_by(email=email).first()
        if user:
            return render_template('accounts/register.html',
                                   msg='Email already registered',
                                   success=False,
                                   form=create_account_form)

        # else we can create the user
        user = Users(**request.form)
        db.session.add(user)
        db.session.commit()

        # Delete user from session
        logout_user()

        return render_template('accounts/register.html',
                               msg='User created successfully.',
                               success=True,
                               form=create_account_form)

    else:
        return render_template('accounts/register.html', form=create_account_form)


@blueprint.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('authentication_blueprint.login')) 

# Errors

@login_manager.unauthorized_handler
def unauthorized_handler():
    return render_template('home/page-403.html'), 403


@blueprint.errorhandler(403)
def access_forbidden(error):
    return render_template('home/page-403.html'), 403


@blueprint.errorhandler(404)
def not_found_error(error):
    return render_template('home/page-404.html'), 404


@blueprint.errorhandler(500)
def internal_error(error):
    return render_template('home/page-500.html'), 500

apps/home/__init__.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask import Blueprint

blueprint = Blueprint(
    'home_blueprint',
    __name__,
    url_prefix=''
)

apps/home/routes.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from apps.home import blueprint
from flask import render_template, request
from flask_login import login_required
from jinja2 import TemplateNotFound


@blueprint.route('/index')
@login_required
def index():

    return render_template('home/index.html', segment='index')


@blueprint.route('/<template>')
@login_required
def route_template(template):

    try:

        if not template.endswith('.html'):
            template += '.html'

        # Detect the current page
        segment = get_segment(request)

        # Serve the file (if exists) from app/templates/home/FILE.html
        return render_template("home/" + template, segment=segment)

    except TemplateNotFound:
        return render_template('home/page-404.html'), 404

    except:
        return render_template('home/page-500.html'), 500


# Helper - Extract current page name from request
def get_segment(request):

    try:

        segment = request.path.split('/')[-1]

        if segment == '':
            segment = 'index'

        return segment

    except:
        return None

apps/templates/accounts/login.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Login {% endblock %}

{% block content %} 

	<!-- [ auth-signin ] start -->
	<div class="auth-wrapper">
		<div class="auth-content">
			<div class="card">
				<div class="row align-items-center text-center">
					<div class="col-md-12">
						<div class="card-body">
							<img src="/static/assets/images/logo-dark.png" alt="" class="img-fluid mb-4">

							<h4 class="mb-3 f-w-400">Sign IN</h4>
							<span class="mb-2 text-muted">
								{% if msg %}
									<span class="text-danger">
										{{ msg | safe }}
									</span>
								{% else %}
									Add your credentials
								{% endif %} 
							</span>

							<br /><br />

							<form role="form" method="post" action="">

								{{ form.hidden_tag() }} 

								<div class="input-group mb-3">
									<span class="input-group-text"><i class="feather icon-user"></i></span>
									{{ form.username(placeholder="Username", class="form-control") }}
								</div>
								<div class="input-group mb-4">
									<span class="input-group-text"><i class="feather icon-lock"></i></span>
									{{ form.password(placeholder="Password", class="form-control", type="password") }}
								</div>

								<button type="submit" name="login" class="btn btn-block btn-primary mt-2 mb-4">Sign In</button>
							
							</form>

							<p class="mb-2">Don't have an account? <a href="{{ url_for('authentication_blueprint.register') }}" class="f-w-400">Sign UP</a></p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- [ auth-signin ] end -->

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %} 

apps/templates/accounts/register.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Sign UP {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

	<!-- [ auth-signup ] start -->
	<div class="auth-wrapper">
		<div class="auth-content">
			<div class="card">
				<div class="row align-items-center text-center">
					<div class="col-md-12">
						<div class="card-body">
							<img src="/static/assets/images/logo-dark.png" alt="" class="img-fluid mb-4">

							<h4 class="mb-3 f-w-400">Sign UP</h4>

							<span class="mb-0 text-muted">
								{% if msg %}
									<span class="text-danger">
										{{ msg | safe }}
									</span>
								{% else %}
									Add your credentials
								{% endif %} 
							</span>
							
							<br /><br />

							{% if success %}
								<p class="mb-2">
									<a class="btn btn-primary btn-block mt-2 mb-4" href="{{ url_for('authentication_blueprint.login') }}" class="f-w-400">Sign IN</a>
								</p>
							{% else %}

								<form role="form" method="post" action="">

									{{ form.hidden_tag() }}

									<div class="input-group mb-3">
										<span class="input-group-text"><i class="feather icon-user"></i></span>
										{{ form.username(placeholder="Username", class="form-control") }}
									</div>
									<div class="input-group mb-3">
										<span class="input-group-text"><i class="feather icon-mail"></i></span>
										{{ form.email(placeholder="Email", class="input form-control", type="email") }}
									</div>
									<div class="input-group mb-4">
										<span class="input-group-text"><i class="feather icon-lock"></i></span>
										{{ form.password(placeholder="Password", class="form-control", type="password") }}
									</div>

									<button type="submit" name="register" class="btn btn-primary btn-block mt-2 mb-4">Sign UP</button>
									<p class="mb-2">
										Already have an account? <a href="{{ url_for('authentication_blueprint.login') }}" class="f-w-400">Sign IN</a>
									</p>
								
								</form>

							{% endif %}	
							
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- [ auth-signup ] end -->

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/home/auth-signin.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Sign IN {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

	<!-- [ auth-signin ] start -->
	<div class="auth-wrapper">
		<div class="auth-content">
			<div class="card">
				<div class="row align-items-center text-center">
					<div class="col-md-12">
						<div class="card-body">
							<img src="/static/assets/images/logo-dark.png" alt="" class="img-fluid mb-4">
							<h4 class="mb-3 f-w-400">Signin</h4>
							<div class="input-group mb-3">
								<span class="input-group-text"><i class="feather icon-mail"></i></span>
								<input type="email" class="form-control" placeholder="Email address">
							</div>
							<div class="input-group mb-4">
								<span class="input-group-text"><i class="feather icon-lock"></i></span>
								<input type="password" class="form-control" placeholder="Password">
							</div>
							<div class="form-group text-left mt-2">
								<div class="checkbox checkbox-primary d-inline">
									<input type="checkbox" name="checkbox-fill-1" id="checkbox-fill-a1" checked="">
									<label for="checkbox-fill-a1" class="cr"> Save credentials</label>
								</div>
							</div>
							<button class="btn btn-block btn-primary mt-2 mb-4">Signin</button>
							<p class="mb-2 text-muted">Forgot password? <a href="/auth-reset-password.html" class="f-w-400">Reset</a></p>
							<p class="mb-0 text-muted">Don’t have an account? <a href="/auth-signup.html" class="f-w-400">Signup</a></p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- [ auth-signin ] end -->

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/home/auth-signup.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Sign UP {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

	<!-- [ auth-signup ] start -->
	<div class="auth-wrapper">
		<div class="auth-content">
			<div class="card">
				<div class="row align-items-center text-center">
					<div class="col-md-12">
						<div class="card-body">
							<img src="/static/assets/images/logo-dark.png" alt="" class="img-fluid mb-4">
							<h4 class="mb-3 f-w-400">Sign up</h4>
							<div class="input-group mb-3">
								<span class="input-group-text"><i class="feather icon-user"></i></span>
								<input type="text" class="form-control" placeholder="Username">
							</div>
							<div class="input-group mb-3">
								<span class="input-group-text"><i class="feather icon-mail"></i></span>
								<input type="email" class="form-control" placeholder="Email address">
							</div>
							<div class="input-group mb-4">
								<span class="input-group-text"><i class="feather icon-lock"></i></span>
								<input type="password" class="form-control" placeholder="Password">
							</div>
							<div class="form-group text-left mt-2">
								<div class="checkbox checkbox-primary d-inline">
									<input type="checkbox" name="checkbox-fill-2" id="checkbox-fill-2">
									<label for="checkbox-fill-2" class="cr">Send me the <a href="#"> Newsletter</a> weekly.</label>
								</div>
							</div>
							<button class="btn btn-primary btn-block mt-2 mb-4">Sign up</button>
							<p class="mb-2">Already have an account? <a href="/auth-signin.html" class="f-w-400">Signin</a></p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- [ auth-signup ] end -->

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/home/bc_typography.html
{% extends "layouts/base.html" %}

{% block title %} Typography {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

	<!-- [ Main Content ] start -->
	<div class="pcoded-main-container">
		<div class="pcoded-content">
			<!-- [ breadcrumb ] start -->
			<div class="page-header">
				<div class="page-block">
					<div class="row align-items-center">
						<div class="col-md-12">
							<div class="page-header-title">
								<h5 class="m-b-10">Typography</h5>
							</div>
							<ul class="breadcrumb">
								<li class="breadcrumb-item"><a href="/"><i class="feather icon-home"></i></a></li>
								<li class="breadcrumb-item"><a href="#">Basic Components</a></li>
								<li class="breadcrumb-item"><a href="#">Typography</a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
			<!-- [ breadcrumb ] end -->
			<!-- [ Main Content ] start -->
			<div class="row">
				<!-- [ Typography ] start -->
				<div class="col-sm-12">
					<div class="card">
						<div class="card-header">
							<h5>Headings</h5>
						</div>
						<div class="card-body">
							<h1>This is a Heading 1</h1>
							<p class="text-muted mb-4">Suspendisse vel quam malesuada, aliquet sem sit amet, fringilla elit. Morbi tempor tincidunt tempor. Etiam id turpis viverra, vulputate sapien nec, varius sem. Curabitur
								ullamcorper fringilla eleifend. In ut eros hendrerit est consequat posuere et at velit.</p>
							<div class="clearfix"></div>
							<h2>This is a Heading 2</h2>
							<p class="text-muted mb-4">In nec rhoncus eros. Vestibulum eu mattis nisl. Quisque viverra viverra magna nec pulvinar. Maecenas pellentesque porta augue, consectetur facilisis diam porttitor sed.
								Suspendisse tempor est sodales augue rutrum tincidunt. Quisque a malesuada purus.</p>
							<div class="clearfix"></div>
							<h3>This is a Heading 3</h3>
							<p class="text-muted mb-4">Vestibulum auctor tincidunt semper. Phasellus ut vulputate lacus. Suspendisse ultricies mi eros, sit amet tempor nulla varius sed. Proin nisl nisi, feugiat quis bibendum vitae,
								dapibus in tellus.</p>
							<div class="clearfix"></div>
							<h4>This is a Heading 4</h4>
							<p class="text-muted mb-4">Nulla et mattis nunc. Curabitur scelerisque commodo condimentum. Mauris blandit, velit a consectetur egestas, diam arcu fermentum justo, eget ultrices arcu eros vel erat.</p>
							<div class="clearfix"></div>
							<h5>This is a Heading 5</h5>
							<p class="text-muted mb-4">Quisque nec turpis at urna dictum luctus. Suspendisse convallis dignissim eros at volutpat. In egestas mattis dui. Aliquam mattis dictum aliquet. Nulla sapien mauris, eleifend et
								sem ac, commodo dapibus odio. Vivamus pretium nec odio cursus elementum. Suspendisse molestie ullamcorper ornare.
							</p>
							<div class="clearfix"></div>
							<h6>This is a Heading 6</h6>
							<p class="text-muted mb-0">Donec ultricies, lacus id tempor condimentum, orci leo faucibus sem, a molestie libero lectus ac justo. ultricies mi eros, sit amet tempor nulla varius sed. Proin nisl nisi,
								feugiat quis bibendum vitae, dapibus in tellus.
							</p>
						</div>
					</div>
				</div>
				<div class="col-sm-12">
					<div class="card">
						<div class="card-header">
							<h5>Display Headings</h5>
						</div>
						<div class="card-body">
							<h1 class="display-1">Display 1</h1>
							<h1 class="display-2">Display 2</h1>
							<h1 class="display-3">Display 3</h1>
							<h1 class="display-4">Display 4</h1>
						</div>
					</div>
				</div>
				<div class="col-md-6">
					<div class="card">
						<div class="card-header">
							<h5>Inline Text Elements</h5>
						</div>
						<div class="card-body">
							<p class="lead m-t-0">Your title goes here</p>
							You can use the mark tag to
							<mark>highlight</mark> text.
							<br>
							<del>This line of text is meant to be treated as deleted text.</del>
							<br>
							<ins>This line of text is meant to be treated as an addition to the document.</ins>
							<br>
							<strong>rendered as bold text</strong>
							<br>
							<em>rendered as italicized text</em>
						</div>
					</div>
				</div>
				<div class="col-md-6">
					<div class="card">
						<div class="card-header">
							<h5>Contextual Text Colors</h5>
						</div>
						<div class="card-body">
							<p class="text-muted mb-1">
								Fusce dapibus, tellus ac cursus commodo, tortor mauris nibh.
							</p>
							<p class="text-primary mb-1">
								Nullam id dolor id nibh ultricies vehicula ut id elit.
							</p>
							<p class="text-success mb-1">
								Duis mollis, est non commodo luctus, nisi erat porttitor ligula.
							</p>
							<p class="text-info mb-1">
								Maecenas sed diam eget risus varius blandit sit amet non magna.
							</p>
							<p class="text-warning mb-1">
								Etiam porta sem malesuada magna mollis euismod.
							</p>
							<p class="text-danger mb-1">
								Donec ullamcorper nulla non metus auctor fringilla.
							</p>
							<p class="text-dark mb-1">
								Nullam id dolor id nibh ultricies vehicula ut id elit.
							</p>
						</div>
					</div>
				</div>
				<div class="col-md-6 col-lg-4">
					<div class="card">
						<div class="card-header">
							<h5>Unordered</h5>
						</div>
						<div class="card-body">
							<ul>
								<li>Lorem ipsum dolor sit amet</li>
								<li>Consectetur adipiscing elit</li>
								<li>Integer molestie lorem at massa</li>
								<li>Facilisis in pretium nisl aliquet</li>
								<li>Nulla volutpat aliquam velit
									<ul>
										<li>Phasellus iaculis neque</li>
										<li>Purus sodales ultricies</li>
										<li>Vestibulum laoreet porttitor sem</li>
										<li>Ac tristique libero volutpat at</li>
									</ul>
								</li>
								<li>Faucibus porta lacus fringilla vel</li>
								<li>Aenean sit amet erat nunc</li>
								<li>Eget porttitor lorem</li>
							</ul>
						</div>
					</div>
				</div>
				<div class="col-md-6 col-lg-4">
					<div class="card">
						<div class="card-header">
							<h5>Ordered</h5>
						</div>
						<div class="card-body">
							<ol>
								<li>Lorem ipsum dolor sit amet</li>
								<li>Consectetur adipiscing elit</li>
								<li>Integer molestie lorem at massa</li>
								<li>Facilisis in pretium nisl aliquet</li>
								<li>Nulla volutpat aliquam velit
									<ul>
										<li>Phasellus iaculis neque</li>
										<li>Purus sodales ultricies</li>
										<li>Vestibulum laoreet porttitor sem</li>
										<li>Ac tristique libero volutpat at</li>
									</ul>
								</li>
								<li>Faucibus porta lacus fringilla vel</li>
								<li>Aenean sit amet erat nunc</li>
								<li>Eget porttitor lorem</li>
							</ol>
						</div>
					</div>
				</div>
				<div class="col-md-12 col-lg-4">
					<div class="card">
						<div class="card-header">
							<h5>Unstyled</h5>
						</div>
						<div class="card-body">
							<ul class="list-unstyled">
								<li>Lorem ipsum dolor sit amet</li>
								<li>Integer molestie lorem at massa
									<ul>
										<li>Phasellus iaculis neque</li>
									</ul>
								</li>
								<li>Faucibus porta lacus fringilla vel</li>
								<li>Eget porttitor lorem</li>
							</ul>
							<h5>Inline</h5>
							<hr>
							<ul class="list-inline m-b-0">
								<li class="list-inline-item">Lorem ipsum</li>
								<li class="list-inline-item">Phasellus iaculis</li>
								<li class="list-inline-item">Nulla volutpat</li>
							</ul>
						</div>
					</div>
				</div>
				<div class="col-md-6">
					<div class="card">
						<div class="card-header">
							<h5>Blockquotes</h5>
						</div>
						<div class="card-body">
							<p class="text-muted m-b-30">
								Your awesome text goes here.
							</p>
							<blockquote class="blockquote">
								<p class="mb-2">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
								<footer class="blockquote-footer">Someone famous in <cite title="Source Title">Source Title</cite></footer>
							</blockquote>
							<p class="text-muted m-b-15 m-t-20">
								Add <code>.text-end</code> for a blockquote with right-aligned content.
							</p>
							<blockquote class="blockquote text-end">
								<p class="mb-2">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
								<footer class="blockquote-footer">Someone famous in <cite title="Source Title">Source Title</cite></footer>
							</blockquote>
						</div>
					</div>
				</div>
				<div class="col-md-6">
					<div class="card">
						<div class="card-header">
							<h5>Horizontal Description</h5>
						</div>
						<div class="card-body">
							<dl class="dl-horizontal row">
								<dt class="col-sm-3">Description lists</dt>
								<dd class="col-sm-9">A description list is perfect for defining terms.</dd>

								<dt class="col-sm-3">Euismod</dt>
								<dd class="col-sm-9">Vestibulum id ligula porta felis euismod semper eget lacinia odio sem nec elit.</dd>
								<dd class="col-sm-9">Donec id elit non mi porta gravida at eget metus.</dd>

								<dt class="col-sm-3">Malesuada porta</dt>
								<dd class="col-sm-9">Etiam porta sem malesuada magna mollis euismod.</dd>

								<dt class="col-sm-3 text-truncate">Truncated term is truncated</dt>
								<dd class="col-sm-9">Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</dd>
							</dl>
						</div>
					</div>
				</div>
				<!-- [ Typography ] end -->
			</div>
			<!-- [ Main Content ] end -->

		</div>
	</div>
	<!-- [ Main Content ] end -->

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/includes/navigation.html
	<!-- [ Header ] start -->
	<header class="navbar pcoded-header navbar-expand-lg navbar-light headerpos-fixed header-blue">
		
			
        <div class="m-header">
            <a class="mobile-menu" id="mobile-collapse" href="#"><span></span></a>
            <a href="#" class="b-brand">
                <!-- ========   change your logo hear   ============ -->
                <img src="/static/assets/images/logo.png" alt="" class="logo">
                <img src="/static/assets/images/logo-icon.png" alt="" class="logo-thumb">
            </a>
            <a href="#" class="mob-toggler">
                <i class="feather icon-more-vertical"></i>
            </a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a href="#" class="pop-search"><i class="feather icon-search"></i></a>
                    <div class="search-bar">
                        <input type="text" class="form-control border-0 shadow-none" placeholder="Search here">
                        <button type="button" class="btn-close" aria-label="Close">
                        </button>
                    </div>
                </li>
            </ul>
            <ul class="navbar-nav ms-auto">
                <li>
                    <div class="dropdown drp-user">
                        <a href="#" class="dropdown-toggle" data-bs-toggle="dropdown">
                            <img src="/static/assets/images/user/avatar-1.jpg" class="img-radius wid-40"
                                alt="User-Profile-Image">
                        </a>
                        <div class="dropdown-menu dropdown-menu-end profile-notification">
                            <div class="pro-head">
                                <img src="/static/assets/images/user/avatar-1.jpg" class="img-radius"
                                    alt="User-Profile-Image">
                                <span>
                                    {{ current_user.username }}
                                </span>
                            </div>
                            <ul class="pro-body">
                                <li>
                                    <a href="{{ url_for('authentication_blueprint.logout') }}" 
                                       class="dropdown-item"><i
                                            class="feather icon-lock"></i> Logout</a></li>
                            </ul>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
        
    
</header>
<!-- [ Header ] end -->

apps/templates/includes/scripts.html
    <script src="/static/assets/js/plugins/popper.min.js"></script>
    <script src="/static/assets/js/plugins/perfect-scrollbar.min.js"></script>
    <script src="/static/assets/js/plugins/bootstrap.min.js"></script>
    <script src="/static/assets/js/pcoded.js"></script>
    